package org.ywzj.rvp.firesupport.server;

/** 服务端拒绝或任务终止原因；枚举序号用于当前网络协议。 */
public enum RVP_FireSupportEndReason {
    NONE,
    INVALID_PACKET,
    STALE_REVISION,
    TERMINAL_NOT_HELD,
    TERMINAL_DUPLICATED,
    PROFILE_NOT_FOUND,
    PROFILE_AMBIGUOUS,
    SELECTION_NOT_FOUND,
    WEAPON_UNAVAILABLE,
    INVALID_TARGET,
    TARGET_OUT_OF_RANGE,
    INVALID_PARAMETERS,
    INVALID_SCHEDULE,
    PLAYER_MISSION_LIMIT,
    GLOBAL_MISSION_LIMIT,
    REQUEST_COOLDOWN,
    NONCE_CONFLICT,
    PLAYER_DIED,
    PLAYER_DISCONNECTED,
    TERMINAL_LOST,
    CEASE_FIRE_NOT_ALLOWED,
    CHUNK_LIMIT,
    CHUNK_TIMEOUT,
    DELIVERY_UNSUPPORTED,
    DELIVERY_FAILED,
    OUTSIDE_WORLD,
    COMPLETED,
    CEASED,
    USER_CANCELLED
}
