package org.ywzj.rvp.firesupport.server;

/** 服务端拒绝或任务终止原因；枚举序号用于当前网络协议。 */
public enum RVP_FireSupportEndReason {
    NONE,
    INVALID_PACKET,
    STALE_REVISION,
    TERMINAL_NOT_HELD,
    TERMINAL_DUPLICATED,
    PROFILE_NOT_FOUND,
    PROFILE_AMBIGUOUS,
    SELECTION_NOT_FOUND,
    WEAPON_UNAVAILABLE,
    INVALID_TARGET,
    TARGET_OUT_OF_RANGE,
    INVALID_PARAMETERS,
    INVALID_SCHEDULE,
    PLAYER_MISSION_LIMIT,
    GLOBAL_MISSION_LIMIT,
    REQUEST_COOLDOWN,
    NONCE_CONFLICT,
    PLAYER_DIED,
    PLAYER_DISCONNECTED,
    TERMINAL_LOST,
    CEASE_FIRE_NOT_ALLOWED,
    CHUNK_LIMIT,
    CHUNK_TIMEOUT,
    DELIVERY_UNSUPPORTED,
    DELIVERY_FAILED,
    TRAJECTORY_UNREACHABLE,
    OUTSIDE_WORLD,
    COMPLETED,
    CEASED,
    USER_CANCELLED,
    /** 指定空中支援飞机被击落，未投送的计划立即终止。 */
    AIRCRAFT_DESTROYED,
    /** 空中支援飞机加入世界或初始化失败，尚未进入可观测存活状态。 */
    AIRCRAFT_SPAWN_FAILED,
    /** 空中支援飞机运行中非毁伤性失联，且未能在恢复窗口内重新出现。 */
    AIRCRAFT_LOST
}
